### ISSUE TITLE
`video.repliesCount`, `parentComment.repliesCount` and `parentComment.reactionsAndRepiesCount` not updated when comment is excluded/restored

### ISSUE THREAD

**Issue by Lezek123** [Joystream/orion#92]
SSIA

**Comment by Lezek123** [comment]
Fixed in https://github.com/Joystream/orion/pull/49/commits/813d623f55c8d7f068523fa8210051396f05dd97.
@drillprop Please test it once I update `atlas-dev` and close if it works as expected.

**Comment by drillprop** [comment]
I still see one issue, unfortunately. 

I excluded one parent's comment, and everything was fine. 
When I exclude the reply to the comment I got negative values
![image](https://user-images.githubusercontent.com/51168865/225313531-828d1a39-401a-45a9-ba18-a43fffc1adc3.png)
Comment id `METAPROTOCOL-OLYMPIA-218788-2`

**Comment by drillprop** [comment]
Video: 
![image](https://user-images.githubusercontent.com/51168865/225314450-0fdcd3dc-d96b-4cd5-b30d-8a3d9d039313.png)

**Comment by Lezek123** [comment]
It think it was due to the same exclusion possibly being processed multiple times. I fixed this case in: https://github.com/Joystream/orion/pull/49/commits/cb3f1a232ead85e9eb98cc1cf7cdc09711a3ca03.
